services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  db:
    image: postgres:alpine3.18
    container_name: db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tumiki
    volumes:
      - db_vol:/var/lib/postgresql/data

  db-test:
    image: postgres:alpine3.18
    container_name: db-test
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tumiki_test
    volumes:
      - db_test_vol:/var/lib/postgresql/data

  https-portal:
    image: steveltn/https-portal:1
    ports:
      - "80:80"
      - "443:443"
    environment:
      DOMAINS: "local-server.tumiki.cloud -> http://host.docker.internal:8080"
      STAGE: "local"
      CUSTOM_NGINX_GLOBAL_HTTP_CONFIG_BLOCK: |
        proxy_buffering off;
        proxy_http_version 1.1;
      CUSTOM_NGINX_LOCATION_CONFIG_BLOCK: |
        proxy_read_timeout 86400s;
        proxy_send_timeout 86400s;
        proxy_connect_timeout 5s;
        proxy_set_header Connection '';
        proxy_set_header Cache-Control 'no-cache';
        proxy_set_header X-Accel-Buffering 'no';
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $host;
        chunked_transfer_encoding off;
    volumes:
      - https-portal-data:/var/lib/https-portal
    restart: always

volumes:
  db_vol:
  db_test_vol:
  https-portal-data:
